### ISSUE TITLE
[Feat]: 그룹 관련 기능 구현

### ISSUE THREAD

**Issue by ojj1123** [Endless-Creation-32nd/refill-front#10]
## 기능 설명
- 그룹 관련 기능을 구현합니다.
<img width="463" alt="스크린샷 2022-07-24 15 22 07" src="https://user-images.githubusercontent.com/33178048/180635063-2b7166ae-5a2c-4caa-aeda-8a2643e773f5.png">

## Tasks
- [x] 그룹 추천 조회 페이지 디자인 및 api 연동
- [x] 그룹 상세 조회 페이지 디자인
- [x] 그룹 상세 조회 api 연동
- [x] 그룹 만들기 페이지 디자인 및 api 연동
- [x] 그룹 검색 페이지 디자인
