### ISSUE TITLE
[Feat]: 홈화면 디자인 및 기능 구현

### ISSUE THREAD

**Issue by ojj1123** [Endless-Creation-32nd/refill-front#14]
## 기능 설명
- 홈화면에서 사용자가 가입한 그룹이 없을 시, 추천 그룹 목록을 보여줍니다.
- 가입한 그룹이 있을 시, 내 그룹 정보를 보여줍니다.
<img width="240" alt="스크린샷 2022-07-25 00 27 23" src="https://user-images.githubusercontent.com/33178048/180654288-1415881f-ac2e-4a3c-8f83-d08c6efa68fc.png">

## Tasks
- [x] 가입한 그룹 있을 시, 그룹 추천 보여주기
- [x] 가입한 그룹 없을 시, 내 그룹 보여주기
- [x] 추천 그룹 누를 시, 그룹 상세 페이지로 이동
- [x] 그룹에 가입 요청하기
