### ISSUE TITLE
[Fix]: 7/17 피드백 반영

### ISSUE THREAD

**Issue by ojj1123** [Endless-Creation-32nd/refill-front#4]
## 기능 설명
- 7/17 회의 때 받은 피드백 반영을 합니다.

## Tasks
- [x] 글감 페이지 태그 위아래 간격
- [x] 제목이 너무 길 경우, ... 으로 표시
- [x] 책 표지와 글 간격 조정
