### ISSUE TITLE
[Design]: 레이아웃 컴포넌트 수정

### ISSUE THREAD

**Issue by ojj1123** [Endless-Creation-32nd/refill-front#5]
## 기능 설명
- `header`, `main`, `Navigator` 를 기준으로 레이아웃을 나눕니다.
- 각 navigation tab마다 다른 레이아웃 컴포넌트를 가져갑니다. 또한 동일한 레이아웃 컴포넌트로 감싸진 페이지 컴포넌트는 페이지 전환 시에도 상태가 유지되므로 그 이점을 최대한 살립니다. ([참고-next.js docs](https://nextjs.org/docs/basic-features/layouts#per-page-layouts))
- `header`가 페이지마다 약간씩 다르므로 비슷한 디자인과 구조일 경우에는 필요한 기능(제출버튼, 뒤로가기 버튼 등)을 `props`로 받습니다.
- 동일한 레이아웃 일지라도 `header`가 페이지에 따라 완전히 다른 디자인과 기능을 가지는 경우에는 따로 `header`를 구성합니다.

## Tasks
- [x] Auth layout 제작
- [x] Main Page layout 제작
- [x] Writing(글감) Page layout 제작
- [x] Group page layout 제작
- [x] Mypage  layout 제작
- [x] 같은 레이아웃 다른 디자인, 기능을 가지는 header 컴포넌트 따로 제작
- [x] `Navigator` 디자인
